/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts,scss,css}', // Include your library's components
  ],
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      {
        platfrmr: {
          "primary": "#43b600",
          "secondary": "#ff6600",
          "accent": "#00ffff",
          "neutral": "#ffffff",
          "base-100": "#3a3a3a",
          "info": "#0000ff",
          "success": "#43b600",
          "warning": "#ff6600",
          "error": "#ff0000",
          },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
  plugins: [require('daisyui')],
}

